import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ThemeProviderUp from "@/Components/ThemeProviderUp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProviderUp>{children}</ThemeProviderUp>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
